In [225]:
# import get_cluster_centres
import numpy as np
import pickle
from sklearn.cluster import KMeans
from sklearn.cluster import MiniBatchKMeans as kmn
import os

In [226]:
test="Test.sift"
cluster="../files/centroids/KMeans_4000"
kmean_names="../files/Names_4000"

In [227]:
def generate_clusters(vocab, n_clusters = 500):
    kmeans = kmn(n_clusters).fit(vocab)
    return kmeans

In [228]:
def generate_features(temp_list, kmeans, n_clusters):
    
    t_length = len(temp_list)
    p_array = np.zeros((1,n_clusters))

    for i in range(0, t_length):

        features = temp_list[i]
        print(features.shape)
        (x1,y1)=features.shape
        t_array = np.zeros((1, n_clusters)) #an array for each image
        for j in range(x1):
            des = features[j]
            des = des.reshape(1, 128)
            ind = kmeans.predict(des)
            t_array[0][ind] += 1

        p_array = np.vstack((p_array, t_array))
    
    p_array = p_array[1:]
    return p_array

In [229]:
f= open(cluster,"rb")#cluster repesents the address of  minibatch kmean object pickle
kmeans=pickle.load(f)
f.close()

In [230]:
f= open(test,"rb")#Retieve SIFT feature Dictionary pickle made from retrieve.py
dic=pickle.load(f)
f.close()

In [231]:
sv=[] #Converting to required formats
Names=[]
for k in list(dic):
    for j in list(dic[k]):
        sv.append(dic[k][j])# sv is the sift descriptor of each image
        Names.append([k,j])

In [232]:
histo_grm=generate_features(sv,kmeans,4000)

(46, 128)
(27, 128)
(399, 128)
(1599, 128)
(41, 128)
(376, 128)
(368, 128)
(391, 128)
(1816, 128)
(113, 128)
(3686, 128)
(41, 128)
(534, 128)
(3661, 128)
(40, 128)


In [233]:
hs= np.array(histo_grm)

In [234]:
from sklearn.feature_extraction.text import TfidfTransformer
tfr = TfidfTransformer(smooth_idf=False)
transf=tfr.fit_transform(hs)#############################################
k= transf.toarray()

/usr/local/lib/python3.5/dist-packages/sklearn/feature_extraction/text.py:1242: RuntimeWarning: divide by zero encountered in true_divide
  idf = np.log(n_samples / df) + 1


In [235]:
f= open(kmean_names,"rb")
names=pickle.load(f)#Names of each train input
f.close()

In [236]:
print(names)

[['vo5_split_ends_anti_breakage_shampoo', 'N1_171.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N2_114.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N1_36.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N1_249.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N2_270.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N2_330.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N1_351.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N2_255.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N2_126.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N2_69.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N2_171.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N2_174.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N2_282.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N2_291.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N1_213.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N2_348.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N2_39.jpg'], ['vo5_split_ends_anti_breakage_shampoo', 'N1_30.jp

In [237]:
Names[10]

['tr', 'hard_single_3.jpg']

In [238]:
type(names)

list

In [239]:
names= np.array(names)

In [240]:
K= names[:,0]

In [241]:
K

array(['vo5_split_ends_anti_breakage_shampoo',
       'vo5_split_ends_anti_breakage_shampoo',
       'vo5_split_ends_anti_breakage_shampoo', ...,
       'coca_cola_glass_bottle', 'coca_cola_glass_bottle',
       'coca_cola_glass_bottle'], dtype='<U36')

In [242]:
s= np.random.permutation(len(K))

In [243]:
print(s)
print(np.shape(s))

[3194 1267 1374 ... 1200 1222 2731]
(3456,)


In [244]:
#f=open("Histo.hiss","rb")
#Arr= np.array(pickle.load(f))

# from sklearn.feature_extraction.text import TfidfTransformer
# tfr = TfidfTransformer(smooth_idf=False)
# transf=tfr.fit_transform(Arr)
print(Arr.shape)
k= transf.toarray()
f.close()
X=Arr[s]

(3456, 4000)


In [245]:
print(len(X) )
print(X[0])

3456
[0. 0. 0. ... 0. 0. 0.]


In [246]:
from sklearn import preprocessing
scaler = preprocessing.StandardScaler().fit(X)
X = scaler.transform(X)

In [247]:
k1=np.vstack([tfk,Arr])
from sklearn import preprocessing
sclr = preprocessing.StandardScaler().fit(k1)
k1 = sclr.transform(k1)
from sklearn.feature_extraction.text import TfidfTransformer
tfr = TfidfTransformer(smooth_idf=False)
transf=tfr.fit_transform(k1)
k1= transf.toarray()
print(k1.shape)
tf=k1[len(tfk):]

/usr/local/lib/python3.5/dist-packages/sklearn/feature_extraction/text.py:1242: RuntimeWarning: divide by zero encountered in true_divide
  idf = np.log(n_samples / df) + 1


(3471, 4000)


In [248]:
print(len(X) )
print(X[0])

3456
[-0.25868135 -0.19171338 -0.64677337 ... -0.21151838 -0.19177604
 -0.24687219]


In [249]:
Y= K[s]

In [250]:
s

array([3194, 1267, 1374, ..., 1200, 1222, 2731])

In [251]:
print(Y.shape)

(3456,)


In [252]:
from sklearn.model_selection import train_test_split  
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.20)  

In [253]:
print(y_train)

['cheez_it_white_cheddar' 'vo5_split_ends_anti_breakage_shampoo'
 'vo5_extra_body_volumizing_shampoo' ... 'campbells_chicken_noodle_soup'
 'detergent' 'cheez_it_white_cheddar']


In [254]:
'''from sklearn.svm import SVC  
svclassifier = SVC(kernel='rbf')  
svclassifier.fit(X_train, y_train)  
'''
from sklearn.svm import LinearSVC

In [255]:
# for c in np.arange(0.0001, 0.1, 0.00198):
#     clf = LinearSVC(random_state=0, C=c)
#     clf.fit(X_train, y_train)
#     predict = clf.predict(X_test)
#     print ("C =", c, ",\t Accuracy:", np.mean(predict == y_test)*100, "%")

In [256]:
clf = LinearSVC(random_state=0, C=0.00604)
clf.fit(X_train, y_train)

LinearSVC(C=0.00604, class_weight=None, dual=True, fit_intercept=True,
     intercept_scaling=1, loss='squared_hinge', max_iter=1000,
     multi_class='ovr', penalty='l2', random_state=0, tol=0.0001,
     verbose=0)

In [257]:
print(np.shape(y_train))

(2764,)


In [258]:
y_pred = clf.predict(X_test)
from sklearn.metrics import classification_report, confusion_matrix  
print(confusion_matrix(y_test, y_pred))  
print(classification_report(y_test, y_pred))

[[45  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0 38  0  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0 46  0  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0 40  0  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0 49  0  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0 47  0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0 38  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 48  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0 47  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0 41  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0 35  0  0  0  0  0]
 [ 0  0  0  0  0  1  0  0  0  0  0 33  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 42  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0 53  0  0]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 42  1]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0  5 41]]
                                      precision    recall  f1-score   support

         3m_high_tack_spray_adhesive       1.00      1.00      1.00        45
          aunt_jemima_orig

In [259]:
nampoo=np.array(names)
nampoo[:,1]

array(['N1_171.jpg', 'N2_114.jpg', 'N1_36.jpg', ..., 'N2_354.jpg',
       'N1_72.jpg', 'N2_24.jpg'], dtype='<U36')

In [260]:
s= np.unique(nampoo[:,0])

In [261]:
nampoo.shape

(3456, 2)

In [262]:
nmidx=np.zeros(len(s))
for j in range(len(s)):
    for c in range(len(s)):
        if s[j]==nampoo[c*216][0]:
            nmidx[j]=c
nmidx

array([ 4.,  9.,  7.,  6.,  1.,  5., 15., 12., 11., 10.,  3.,  8., 13.,
        2., 14.,  0.])

In [263]:
y_pred_score=clf.decision_function(X_test)
y_pred_score1=y_pred_score
y_pred_score

array([[-0.56155224, -0.71114892,  2.54518956, ..., -1.08081627,
        -0.91932823, -0.83409686],
       [-0.66685121, -1.16512853, -1.1081157 , ..., -1.31896178,
        -0.86496802, -1.19508632],
       [-0.54078582, -0.88579062, -0.90368142, ..., -0.4681521 ,
        -0.93361492, -0.89102772],
       ...,
       [-0.37454625, -0.68563208, -0.31476072, ..., -0.71301783,
        -1.15811584, -0.11811562],
       [ 1.62401084, -0.96111052, -0.48811431, ..., -0.80669036,
        -1.20980705, -0.73331873],
       [-0.87291682, -0.70370852, -1.10348303, ..., -1.16463017,
        -0.94907091, -0.64650403]])

In [264]:
print(np.shape(y_pred_score))
print(np.shape(X_test))

(692, 16)
(692, 4000)


In [265]:
y_pred_score1

array([[-0.56155224, -0.71114892,  2.54518956, ..., -1.08081627,
        -0.91932823, -0.83409686],
       [-0.66685121, -1.16512853, -1.1081157 , ..., -1.31896178,
        -0.86496802, -1.19508632],
       [-0.54078582, -0.88579062, -0.90368142, ..., -0.4681521 ,
        -0.93361492, -0.89102772],
       ...,
       [-0.37454625, -0.68563208, -0.31476072, ..., -0.71301783,
        -1.15811584, -0.11811562],
       [ 1.62401084, -0.96111052, -0.48811431, ..., -0.80669036,
        -1.20980705, -0.73331873],
       [-0.87291682, -0.70370852, -1.10348303, ..., -1.16463017,
        -0.94907091, -0.64650403]])

In [266]:
print(y_pred)

['campbells_chicken_noodle_soup' 'nutrigrain_apple_cinnamon'
 'clif_crunch_chocolate_chip' 'campbells_chicken_noodle_soup'
 'pringles_bbq' 'clif_crunch_chocolate_chip' 'nutrigrain_apple_cinnamon'
 '3m_high_tack_spray_adhesive' 'clif_crunch_chocolate_chip'
 'expo_marker_red' 'vo5_extra_body_volumizing_shampoo'
 'cheez_it_white_cheddar' 'cholula_chipotle_hot_sauce' 'listerine_green'
 'pringles_bbq' 'vo5_extra_body_volumizing_shampoo'
 'nutrigrain_apple_cinnamon' 'cheez_it_white_cheddar' 'palmolive_green'
 '3m_high_tack_spray_adhesive' 'nutrigrain_apple_cinnamon'
 'cheez_it_white_cheddar' 'expo_marker_red' 'coca_cola_glass_bottle'
 '3m_high_tack_spray_adhesive' 'palmolive_green'
 'aunt_jemima_original_syrup' 'pringles_bbq' 'expo_marker_red'
 'nice_honey_roasted_almonds' 'nice_honey_roasted_almonds'
 'cholula_chipotle_hot_sauce' 'nutrigrain_apple_cinnamon'
 '3m_high_tack_spray_adhesive' 'expo_marker_red'
 'cholula_chipotle_hot_sauce' 'palmolive_green'
 'nutrigrain_apple_cinnamon' 'palmoliv

In [267]:
print(y_pred_score)

[[-0.56155224 -0.71114892  2.54518956 ... -1.08081627 -0.91932823
  -0.83409686]
 [-0.66685121 -1.16512853 -1.1081157  ... -1.31896178 -0.86496802
  -1.19508632]
 [-0.54078582 -0.88579062 -0.90368142 ... -0.4681521  -0.93361492
  -0.89102772]
 ...
 [-0.37454625 -0.68563208 -0.31476072 ... -0.71301783 -1.15811584
  -0.11811562]
 [ 1.62401084 -0.96111052 -0.48811431 ... -0.80669036 -1.20980705
  -0.73331873]
 [-0.87291682 -0.70370852 -1.10348303 ... -1.16463017 -0.94907091
  -0.64650403]]


In [268]:
y_sorted_score=y_pred_score
for i in range(np.shape(X_test)[0]):
    y_sorted_score[i]=np.argsort(-y_pred_score[i])
    
print(y_sorted_score)

[[ 2.  0.  7. ...  9.  8. 13.]
 [11.  0.  6. ... 13.  3.  7.]
 [ 5. 11. 12. ...  2. 14.  6.]
 ...
 [ 5.  9. 10. ...  8. 11. 14.]
 [ 0.  5.  2. ...  1. 14.  3.]
 [ 7.  8. 15. ...  2. 13.  3.]]


In [269]:
for i in range(np.shape(X_test)[0]):
    print(i)
    for j in y_sorted_score[i]:
        print(s[int(j)])

0
campbells_chicken_noodle_soup
3m_high_tack_spray_adhesive
detergent
coca_cola_glass_bottle
aunt_jemima_original_syrup
nutrigrain_apple_cinnamon
clif_crunch_chocolate_chip
palmolive_green
vo5_split_ends_anti_breakage_shampoo
nice_honey_roasted_almonds
cheez_it_white_cheddar
vo5_extra_body_volumizing_shampoo
cholula_chipotle_hot_sauce
listerine_green
expo_marker_red
pringles_bbq
1
nutrigrain_apple_cinnamon
3m_high_tack_spray_adhesive
coca_cola_glass_bottle
vo5_extra_body_volumizing_shampoo
expo_marker_red
clif_crunch_chocolate_chip
campbells_chicken_noodle_soup
cholula_chipotle_hot_sauce
listerine_green
aunt_jemima_original_syrup
vo5_split_ends_anti_breakage_shampoo
palmolive_green
nice_honey_roasted_almonds
pringles_bbq
cheez_it_white_cheddar
detergent
2
clif_crunch_chocolate_chip
nutrigrain_apple_cinnamon
palmolive_green
pringles_bbq
3m_high_tack_spray_adhesive
listerine_green
nice_honey_roasted_almonds
expo_marker_red
cheez_it_white_cheddar
cholula_chipotle_hot_sauce
detergent
aunt_

palmolive_green
coca_cola_glass_bottle
aunt_jemima_original_syrup
cholula_chipotle_hot_sauce
clif_crunch_chocolate_chip
cheez_it_white_cheddar
campbells_chicken_noodle_soup
vo5_split_ends_anti_breakage_shampoo
3m_high_tack_spray_adhesive
vo5_extra_body_volumizing_shampoo
expo_marker_red
nutrigrain_apple_cinnamon
47
campbells_chicken_noodle_soup
pringles_bbq
vo5_split_ends_anti_breakage_shampoo
3m_high_tack_spray_adhesive
nice_honey_roasted_almonds
coca_cola_glass_bottle
cholula_chipotle_hot_sauce
palmolive_green
vo5_extra_body_volumizing_shampoo
nutrigrain_apple_cinnamon
expo_marker_red
clif_crunch_chocolate_chip
listerine_green
detergent
aunt_jemima_original_syrup
cheez_it_white_cheddar
48
expo_marker_red
vo5_extra_body_volumizing_shampoo
3m_high_tack_spray_adhesive
campbells_chicken_noodle_soup
nutrigrain_apple_cinnamon
nice_honey_roasted_almonds
cheez_it_white_cheddar
clif_crunch_chocolate_chip
coca_cola_glass_bottle
pringles_bbq
cholula_chipotle_hot_sauce
listerine_green
detergent


palmolive_green
listerine_green
cholula_chipotle_hot_sauce
campbells_chicken_noodle_soup
detergent
cheez_it_white_cheddar
vo5_split_ends_anti_breakage_shampoo
vo5_extra_body_volumizing_shampoo
nice_honey_roasted_almonds
expo_marker_red
3m_high_tack_spray_adhesive
69
pringles_bbq
listerine_green
vo5_extra_body_volumizing_shampoo
clif_crunch_chocolate_chip
3m_high_tack_spray_adhesive
detergent
palmolive_green
nutrigrain_apple_cinnamon
expo_marker_red
coca_cola_glass_bottle
cholula_chipotle_hot_sauce
cheez_it_white_cheddar
campbells_chicken_noodle_soup
vo5_split_ends_anti_breakage_shampoo
nice_honey_roasted_almonds
aunt_jemima_original_syrup
70
cholula_chipotle_hot_sauce
vo5_split_ends_anti_breakage_shampoo
listerine_green
coca_cola_glass_bottle
nutrigrain_apple_cinnamon
nice_honey_roasted_almonds
aunt_jemima_original_syrup
vo5_extra_body_volumizing_shampoo
clif_crunch_chocolate_chip
pringles_bbq
3m_high_tack_spray_adhesive
campbells_chicken_noodle_soup
detergent
expo_marker_red
palmolive

cholula_chipotle_hot_sauce
coca_cola_glass_bottle
detergent
vo5_extra_body_volumizing_shampoo
nice_honey_roasted_almonds
vo5_split_ends_anti_breakage_shampoo
expo_marker_red
nutrigrain_apple_cinnamon
3m_high_tack_spray_adhesive
clif_crunch_chocolate_chip
cheez_it_white_cheddar
aunt_jemima_original_syrup
93
nutrigrain_apple_cinnamon
palmolive_green
listerine_green
vo5_extra_body_volumizing_shampoo
nice_honey_roasted_almonds
clif_crunch_chocolate_chip
detergent
pringles_bbq
coca_cola_glass_bottle
expo_marker_red
3m_high_tack_spray_adhesive
campbells_chicken_noodle_soup
vo5_split_ends_anti_breakage_shampoo
aunt_jemima_original_syrup
cholula_chipotle_hot_sauce
cheez_it_white_cheddar
94
pringles_bbq
clif_crunch_chocolate_chip
cholula_chipotle_hot_sauce
vo5_split_ends_anti_breakage_shampoo
detergent
palmolive_green
nice_honey_roasted_almonds
listerine_green
3m_high_tack_spray_adhesive
nutrigrain_apple_cinnamon
vo5_extra_body_volumizing_shampoo
expo_marker_red
cheez_it_white_cheddar
campbells

detergent
nice_honey_roasted_almonds
cheez_it_white_cheddar
nutrigrain_apple_cinnamon
vo5_extra_body_volumizing_shampoo
122
nice_honey_roasted_almonds
palmolive_green
vo5_split_ends_anti_breakage_shampoo
listerine_green
clif_crunch_chocolate_chip
aunt_jemima_original_syrup
pringles_bbq
3m_high_tack_spray_adhesive
detergent
coca_cola_glass_bottle
expo_marker_red
cholula_chipotle_hot_sauce
nutrigrain_apple_cinnamon
campbells_chicken_noodle_soup
cheez_it_white_cheddar
vo5_extra_body_volumizing_shampoo
123
aunt_jemima_original_syrup
coca_cola_glass_bottle
vo5_split_ends_anti_breakage_shampoo
campbells_chicken_noodle_soup
pringles_bbq
clif_crunch_chocolate_chip
nutrigrain_apple_cinnamon
detergent
3m_high_tack_spray_adhesive
palmolive_green
listerine_green
expo_marker_red
nice_honey_roasted_almonds
cheez_it_white_cheddar
vo5_extra_body_volumizing_shampoo
cholula_chipotle_hot_sauce
124
clif_crunch_chocolate_chip
listerine_green
pringles_bbq
expo_marker_red
coca_cola_glass_bottle
vo5_split_end

clif_crunch_chocolate_chip
palmolive_green
expo_marker_red
listerine_green
aunt_jemima_original_syrup
3m_high_tack_spray_adhesive
cheez_it_white_cheddar
coca_cola_glass_bottle
detergent
nutrigrain_apple_cinnamon
campbells_chicken_noodle_soup
nice_honey_roasted_almonds
vo5_split_ends_anti_breakage_shampoo
pringles_bbq
vo5_extra_body_volumizing_shampoo
152
listerine_green
clif_crunch_chocolate_chip
aunt_jemima_original_syrup
detergent
nice_honey_roasted_almonds
expo_marker_red
coca_cola_glass_bottle
cheez_it_white_cheddar
cholula_chipotle_hot_sauce
vo5_split_ends_anti_breakage_shampoo
campbells_chicken_noodle_soup
pringles_bbq
3m_high_tack_spray_adhesive
vo5_extra_body_volumizing_shampoo
nutrigrain_apple_cinnamon
palmolive_green
153
nice_honey_roasted_almonds
aunt_jemima_original_syrup
vo5_split_ends_anti_breakage_shampoo
expo_marker_red
listerine_green
cheez_it_white_cheddar
palmolive_green
3m_high_tack_spray_adhesive
campbells_chicken_noodle_soup
clif_crunch_chocolate_chip
pringles_bbq

nice_honey_roasted_almonds
clif_crunch_chocolate_chip
cheez_it_white_cheddar
pringles_bbq
listerine_green
campbells_chicken_noodle_soup
detergent
3m_high_tack_spray_adhesive
cholula_chipotle_hot_sauce
181
nice_honey_roasted_almonds
3m_high_tack_spray_adhesive
cheez_it_white_cheddar
vo5_split_ends_anti_breakage_shampoo
campbells_chicken_noodle_soup
coca_cola_glass_bottle
palmolive_green
nutrigrain_apple_cinnamon
detergent
aunt_jemima_original_syrup
vo5_extra_body_volumizing_shampoo
expo_marker_red
pringles_bbq
listerine_green
cholula_chipotle_hot_sauce
clif_crunch_chocolate_chip
182
palmolive_green
listerine_green
pringles_bbq
coca_cola_glass_bottle
detergent
cheez_it_white_cheddar
clif_crunch_chocolate_chip
vo5_extra_body_volumizing_shampoo
3m_high_tack_spray_adhesive
campbells_chicken_noodle_soup
cholula_chipotle_hot_sauce
aunt_jemima_original_syrup
nice_honey_roasted_almonds
vo5_split_ends_anti_breakage_shampoo
expo_marker_red
nutrigrain_apple_cinnamon
183
cheez_it_white_cheddar
vo5_

nutrigrain_apple_cinnamon
pringles_bbq
vo5_split_ends_anti_breakage_shampoo
210
nutrigrain_apple_cinnamon
cheez_it_white_cheddar
aunt_jemima_original_syrup
palmolive_green
3m_high_tack_spray_adhesive
vo5_extra_body_volumizing_shampoo
detergent
campbells_chicken_noodle_soup
cholula_chipotle_hot_sauce
expo_marker_red
coca_cola_glass_bottle
clif_crunch_chocolate_chip
nice_honey_roasted_almonds
vo5_split_ends_anti_breakage_shampoo
pringles_bbq
listerine_green
211
expo_marker_red
pringles_bbq
palmolive_green
vo5_extra_body_volumizing_shampoo
aunt_jemima_original_syrup
clif_crunch_chocolate_chip
listerine_green
nutrigrain_apple_cinnamon
coca_cola_glass_bottle
3m_high_tack_spray_adhesive
cholula_chipotle_hot_sauce
cheez_it_white_cheddar
nice_honey_roasted_almonds
detergent
campbells_chicken_noodle_soup
vo5_split_ends_anti_breakage_shampoo
212
clif_crunch_chocolate_chip
listerine_green
pringles_bbq
campbells_chicken_noodle_soup
nutrigrain_apple_cinnamon
3m_high_tack_spray_adhesive
coca_cola_gl

vo5_split_ends_anti_breakage_shampoo
listerine_green
aunt_jemima_original_syrup
3m_high_tack_spray_adhesive
expo_marker_red
cheez_it_white_cheddar
campbells_chicken_noodle_soup
pringles_bbq
cholula_chipotle_hot_sauce
coca_cola_glass_bottle
nutrigrain_apple_cinnamon
clif_crunch_chocolate_chip
detergent
240
vo5_extra_body_volumizing_shampoo
nice_honey_roasted_almonds
campbells_chicken_noodle_soup
palmolive_green
vo5_split_ends_anti_breakage_shampoo
expo_marker_red
aunt_jemima_original_syrup
cholula_chipotle_hot_sauce
clif_crunch_chocolate_chip
3m_high_tack_spray_adhesive
detergent
cheez_it_white_cheddar
pringles_bbq
nutrigrain_apple_cinnamon
coca_cola_glass_bottle
listerine_green
241
nutrigrain_apple_cinnamon
vo5_split_ends_anti_breakage_shampoo
vo5_extra_body_volumizing_shampoo
expo_marker_red
cheez_it_white_cheddar
nice_honey_roasted_almonds
3m_high_tack_spray_adhesive
detergent
palmolive_green
aunt_jemima_original_syrup
coca_cola_glass_bottle
clif_crunch_chocolate_chip
cholula_chipotl

cholula_chipotle_hot_sauce
campbells_chicken_noodle_soup
aunt_jemima_original_syrup
clif_crunch_chocolate_chip
nutrigrain_apple_cinnamon
pringles_bbq
cheez_it_white_cheddar
269
cholula_chipotle_hot_sauce
clif_crunch_chocolate_chip
vo5_split_ends_anti_breakage_shampoo
expo_marker_red
listerine_green
nutrigrain_apple_cinnamon
vo5_extra_body_volumizing_shampoo
pringles_bbq
campbells_chicken_noodle_soup
nice_honey_roasted_almonds
aunt_jemima_original_syrup
cheez_it_white_cheddar
palmolive_green
3m_high_tack_spray_adhesive
coca_cola_glass_bottle
detergent
270
palmolive_green
coca_cola_glass_bottle
cheez_it_white_cheddar
nutrigrain_apple_cinnamon
vo5_extra_body_volumizing_shampoo
vo5_split_ends_anti_breakage_shampoo
expo_marker_red
3m_high_tack_spray_adhesive
clif_crunch_chocolate_chip
pringles_bbq
nice_honey_roasted_almonds
campbells_chicken_noodle_soup
listerine_green
aunt_jemima_original_syrup
detergent
cholula_chipotle_hot_sauce
271
cheez_it_white_cheddar
3m_high_tack_spray_adhesive
camp

298
aunt_jemima_original_syrup
3m_high_tack_spray_adhesive
vo5_split_ends_anti_breakage_shampoo
nutrigrain_apple_cinnamon
pringles_bbq
coca_cola_glass_bottle
clif_crunch_chocolate_chip
vo5_extra_body_volumizing_shampoo
nice_honey_roasted_almonds
campbells_chicken_noodle_soup
detergent
expo_marker_red
cheez_it_white_cheddar
cholula_chipotle_hot_sauce
listerine_green
palmolive_green
299
nutrigrain_apple_cinnamon
vo5_split_ends_anti_breakage_shampoo
clif_crunch_chocolate_chip
pringles_bbq
listerine_green
campbells_chicken_noodle_soup
cheez_it_white_cheddar
aunt_jemima_original_syrup
coca_cola_glass_bottle
detergent
nice_honey_roasted_almonds
palmolive_green
cholula_chipotle_hot_sauce
3m_high_tack_spray_adhesive
vo5_extra_body_volumizing_shampoo
expo_marker_red
300
clif_crunch_chocolate_chip
campbells_chicken_noodle_soup
aunt_jemima_original_syrup
coca_cola_glass_bottle
vo5_extra_body_volumizing_shampoo
vo5_split_ends_anti_breakage_shampoo
nutrigrain_apple_cinnamon
pringles_bbq
cheez_it_wh

palmolive_green
clif_crunch_chocolate_chip
vo5_extra_body_volumizing_shampoo
coca_cola_glass_bottle
3m_high_tack_spray_adhesive
vo5_split_ends_anti_breakage_shampoo
cheez_it_white_cheddar
aunt_jemima_original_syrup
nice_honey_roasted_almonds
nutrigrain_apple_cinnamon
listerine_green
328
expo_marker_red
pringles_bbq
listerine_green
vo5_split_ends_anti_breakage_shampoo
vo5_extra_body_volumizing_shampoo
nutrigrain_apple_cinnamon
cheez_it_white_cheddar
palmolive_green
3m_high_tack_spray_adhesive
cholula_chipotle_hot_sauce
campbells_chicken_noodle_soup
nice_honey_roasted_almonds
coca_cola_glass_bottle
detergent
clif_crunch_chocolate_chip
aunt_jemima_original_syrup
329
nice_honey_roasted_almonds
cholula_chipotle_hot_sauce
coca_cola_glass_bottle
aunt_jemima_original_syrup
campbells_chicken_noodle_soup
detergent
clif_crunch_chocolate_chip
vo5_extra_body_volumizing_shampoo
3m_high_tack_spray_adhesive
palmolive_green
cheez_it_white_cheddar
pringles_bbq
expo_marker_red
vo5_split_ends_anti_breakag

detergent
pringles_bbq
vo5_extra_body_volumizing_shampoo
cheez_it_white_cheddar
357
vo5_split_ends_anti_breakage_shampoo
listerine_green
clif_crunch_chocolate_chip
cholula_chipotle_hot_sauce
nutrigrain_apple_cinnamon
pringles_bbq
detergent
campbells_chicken_noodle_soup
expo_marker_red
palmolive_green
vo5_extra_body_volumizing_shampoo
coca_cola_glass_bottle
cheez_it_white_cheddar
nice_honey_roasted_almonds
3m_high_tack_spray_adhesive
aunt_jemima_original_syrup
358
detergent
expo_marker_red
3m_high_tack_spray_adhesive
pringles_bbq
clif_crunch_chocolate_chip
aunt_jemima_original_syrup
listerine_green
campbells_chicken_noodle_soup
vo5_split_ends_anti_breakage_shampoo
vo5_extra_body_volumizing_shampoo
cholula_chipotle_hot_sauce
nice_honey_roasted_almonds
nutrigrain_apple_cinnamon
palmolive_green
cheez_it_white_cheddar
coca_cola_glass_bottle
359
campbells_chicken_noodle_soup
aunt_jemima_original_syrup
coca_cola_glass_bottle
detergent
vo5_split_ends_anti_breakage_shampoo
palmolive_green
liste

listerine_green
vo5_split_ends_anti_breakage_shampoo
nutrigrain_apple_cinnamon
393
detergent
expo_marker_red
cholula_chipotle_hot_sauce
vo5_split_ends_anti_breakage_shampoo
3m_high_tack_spray_adhesive
campbells_chicken_noodle_soup
coca_cola_glass_bottle
pringles_bbq
palmolive_green
cheez_it_white_cheddar
aunt_jemima_original_syrup
nice_honey_roasted_almonds
nutrigrain_apple_cinnamon
clif_crunch_chocolate_chip
listerine_green
vo5_extra_body_volumizing_shampoo
394
vo5_split_ends_anti_breakage_shampoo
palmolive_green
clif_crunch_chocolate_chip
pringles_bbq
aunt_jemima_original_syrup
detergent
nutrigrain_apple_cinnamon
vo5_extra_body_volumizing_shampoo
3m_high_tack_spray_adhesive
coca_cola_glass_bottle
expo_marker_red
campbells_chicken_noodle_soup
cholula_chipotle_hot_sauce
nice_honey_roasted_almonds
listerine_green
cheez_it_white_cheddar
395
vo5_extra_body_volumizing_shampoo
vo5_split_ends_anti_breakage_shampoo
palmolive_green
nutrigrain_apple_cinnamon
expo_marker_red
pringles_bbq
aunt_je

listerine_green
detergent
445
aunt_jemima_original_syrup
coca_cola_glass_bottle
clif_crunch_chocolate_chip
cholula_chipotle_hot_sauce
vo5_extra_body_volumizing_shampoo
expo_marker_red
campbells_chicken_noodle_soup
pringles_bbq
cheez_it_white_cheddar
listerine_green
detergent
nice_honey_roasted_almonds
nutrigrain_apple_cinnamon
vo5_split_ends_anti_breakage_shampoo
palmolive_green
3m_high_tack_spray_adhesive
446
campbells_chicken_noodle_soup
pringles_bbq
listerine_green
vo5_split_ends_anti_breakage_shampoo
clif_crunch_chocolate_chip
expo_marker_red
nice_honey_roasted_almonds
cholula_chipotle_hot_sauce
coca_cola_glass_bottle
3m_high_tack_spray_adhesive
detergent
aunt_jemima_original_syrup
vo5_extra_body_volumizing_shampoo
nutrigrain_apple_cinnamon
cheez_it_white_cheddar
palmolive_green
447
nutrigrain_apple_cinnamon
vo5_extra_body_volumizing_shampoo
listerine_green
clif_crunch_chocolate_chip
aunt_jemima_original_syrup
nice_honey_roasted_almonds
expo_marker_red
cheez_it_white_cheddar
cholul

coca_cola_glass_bottle
cheez_it_white_cheddar
vo5_extra_body_volumizing_shampoo
expo_marker_red
detergent
pringles_bbq
cholula_chipotle_hot_sauce
palmolive_green
clif_crunch_chocolate_chip
nice_honey_roasted_almonds
vo5_split_ends_anti_breakage_shampoo
campbells_chicken_noodle_soup
475
detergent
cholula_chipotle_hot_sauce
nice_honey_roasted_almonds
aunt_jemima_original_syrup
cheez_it_white_cheddar
coca_cola_glass_bottle
vo5_extra_body_volumizing_shampoo
campbells_chicken_noodle_soup
listerine_green
palmolive_green
vo5_split_ends_anti_breakage_shampoo
expo_marker_red
clif_crunch_chocolate_chip
pringles_bbq
3m_high_tack_spray_adhesive
nutrigrain_apple_cinnamon
476
clif_crunch_chocolate_chip
expo_marker_red
cheez_it_white_cheddar
nutrigrain_apple_cinnamon
pringles_bbq
nice_honey_roasted_almonds
aunt_jemima_original_syrup
coca_cola_glass_bottle
palmolive_green
campbells_chicken_noodle_soup
listerine_green
vo5_split_ends_anti_breakage_shampoo
cholula_chipotle_hot_sauce
detergent
3m_high_tac

clif_crunch_chocolate_chip
detergent
vo5_extra_body_volumizing_shampoo
cheez_it_white_cheddar
palmolive_green
nutrigrain_apple_cinnamon
504
3m_high_tack_spray_adhesive
vo5_split_ends_anti_breakage_shampoo
pringles_bbq
cheez_it_white_cheddar
palmolive_green
detergent
clif_crunch_chocolate_chip
coca_cola_glass_bottle
nice_honey_roasted_almonds
aunt_jemima_original_syrup
listerine_green
cholula_chipotle_hot_sauce
campbells_chicken_noodle_soup
expo_marker_red
nutrigrain_apple_cinnamon
vo5_extra_body_volumizing_shampoo
505
3m_high_tack_spray_adhesive
coca_cola_glass_bottle
vo5_split_ends_anti_breakage_shampoo
palmolive_green
expo_marker_red
aunt_jemima_original_syrup
pringles_bbq
nice_honey_roasted_almonds
listerine_green
campbells_chicken_noodle_soup
detergent
vo5_extra_body_volumizing_shampoo
clif_crunch_chocolate_chip
cheez_it_white_cheddar
nutrigrain_apple_cinnamon
cholula_chipotle_hot_sauce
506
3m_high_tack_spray_adhesive
expo_marker_red
palmolive_green
listerine_green
cholula_chipotle

palmolive_green
campbells_chicken_noodle_soup
592
detergent
expo_marker_red
pringles_bbq
vo5_extra_body_volumizing_shampoo
vo5_split_ends_anti_breakage_shampoo
aunt_jemima_original_syrup
campbells_chicken_noodle_soup
coca_cola_glass_bottle
palmolive_green
cholula_chipotle_hot_sauce
nice_honey_roasted_almonds
nutrigrain_apple_cinnamon
cheez_it_white_cheddar
listerine_green
clif_crunch_chocolate_chip
3m_high_tack_spray_adhesive
593
palmolive_green
nutrigrain_apple_cinnamon
clif_crunch_chocolate_chip
coca_cola_glass_bottle
vo5_extra_body_volumizing_shampoo
pringles_bbq
campbells_chicken_noodle_soup
cholula_chipotle_hot_sauce
expo_marker_red
nice_honey_roasted_almonds
3m_high_tack_spray_adhesive
cheez_it_white_cheddar
detergent
listerine_green
aunt_jemima_original_syrup
vo5_split_ends_anti_breakage_shampoo
594
3m_high_tack_spray_adhesive
clif_crunch_chocolate_chip
listerine_green
vo5_split_ends_anti_breakage_shampoo
detergent
nutrigrain_apple_cinnamon
cholula_chipotle_hot_sauce
palmolive_g

In [270]:
np.shape(X_test)[0]

692

In [271]:
y_pred_score1

array([[ 2.,  0.,  7., ...,  9.,  8., 13.],
       [11.,  0.,  6., ..., 13.,  3.,  7.],
       [ 5., 11., 12., ...,  2., 14.,  6.],
       ...,
       [ 5.,  9., 10., ...,  8., 11., 14.],
       [ 0.,  5.,  2., ...,  1., 14.,  3.],
       [ 7.,  8., 15., ...,  2., 13.,  3.]])

In [272]:
print(hs)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 1. ... 0. 0. 0.]
 [3. 2. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [273]:
print(hs.shape)
k= np.load("../files/tset_Histogram_4000.npy")
tfk=k
k1=np.vstack([k,Arr])
from sklearn.feature_extraction.text import TfidfTransformer
tfr = TfidfTransformer(smooth_idf=False)
transf=tfr.fit_transform(k1)
k1= transf.toarray()
print(k1.shape)
tf=k1[len(k):]
print(tf.shape)
#scaler = preprocessing.StandardScaler().fit(k)


(15, 4000)


/usr/local/lib/python3.5/dist-packages/sklearn/feature_extraction/text.py:1242: RuntimeWarning: divide by zero encountered in true_divide
  idf = np.log(n_samples / df) + 1


(3471, 4000)
(3456, 4000)


In [274]:
k1=k1[0:len(k)]
k = scaler.transform(k)
k.shape
print(k.shape)

(15, 4000)


In [275]:
y_predi = clf.predict(k)  

In [276]:
[print(str(i)+"\t"+y_predi[i]+"\n") for i in range(len(y_predi))]

0	pringles_bbq

1	palmolive_green

2	clif_crunch_chocolate_chip

3	clif_crunch_chocolate_chip

4	listerine_green

5	cholula_chipotle_hot_sauce

6	nice_honey_roasted_almonds

7	listerine_green

8	cheez_it_white_cheddar

9	listerine_green

10	campbells_chicken_noodle_soup

11	expo_marker_red

12	coca_cola_glass_bottle

13	vo5_extra_body_volumizing_shampoo

14	pringles_bbq



[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [277]:
y_pred_score=clf.decision_function(k)
y_pred_score



array([[-6.43605546e+00,  5.70497190e+00,  8.91297365e+00,
         4.19012038e+01, -1.12538888e+00,  3.99426626e+01,
        -6.19402637e+00,  2.05477174e+01, -3.63753087e+00,
         1.51814355e+01,  1.96075645e+01,  2.20957360e+01,
         2.77742324e+00,  4.29134353e+01,  2.16055226e+00,
        -1.08241391e+01],
       [-7.26797662e-01, -9.62244285e-01, -9.49413460e-01,
        -1.05895594e+00, -1.11966036e+00, -9.50522470e-01,
        -1.00654889e+00, -1.38965787e+00, -7.22640235e-01,
        -1.14914104e+00, -1.06040709e+00, -1.43482269e+00,
         2.68393090e+00, -8.50633406e-01, -1.14950825e+00,
        -5.23434363e-01],
       [-5.17037850e-01, -9.72010326e-01, -3.02082038e-01,
        -1.18704916e+00, -9.57239153e-01,  4.79406594e-02,
        -6.78833368e-01, -1.01695120e+00, -6.60844849e-01,
        -1.53004951e+00, -5.29914044e-01, -6.29235217e-01,
        -8.04717104e-01, -1.20336552e+00, -8.25800106e-01,
        -5.75997823e-01],
       [-5.85804792e+00,  6.44837392e

In [278]:
y_sorted_score=y_pred_score
for i in range(np.shape(k)[0]):
    y_sorted_score[i]=np.argsort(-y_pred_score[i])
    
print(y_sorted_score)

[[13.  3.  5. 11.  7. 10.  9.  2.  1. 12. 14.  4.  8.  6.  0. 15.]
 [12. 15.  8.  0. 13.  2.  5.  1.  6.  3. 10.  4.  9. 14.  7. 11.]
 [ 5.  2.  0. 10. 15. 11.  8.  6. 12. 14.  4.  1.  7.  3. 13.  9.]
 [ 5.  3. 13. 11.  7. 10.  9.  2.  1. 12. 14.  4.  8.  6.  0. 15.]
 [ 9.  8.  3. 11. 13.  0.  6.  1.  4. 10.  2. 14.  5. 15.  7. 12.]
 [ 4. 10.  2.  9.  7. 11.  1.  5.  0. 13.  3.  8. 15. 14.  6. 12.]
 [10. 15.  8.  2.  6. 14.  7.  0. 11.  3.  1. 13. 12.  9.  4.  5.]
 [ 9.  8.  3. 13. 11.  4.  1. 10.  2.  6. 12. 14.  7.  5.  0. 15.]
 [ 3. 13.  5.  9. 10.  7. 11.  2.  1. 12.  4.  6. 14.  0.  8. 15.]
 [ 9.  0.  3.  4.  5.  6.  1. 12.  8. 15.  7. 11. 10.  2. 13. 14.]
 [ 2.  8. 10. 15.  4.  6.  0.  5.  9. 11.  1.  7. 14. 13. 12.  3.]
 [ 8. 14.  0. 15. 10.  2.  4.  1.  9.  6.  5.  7. 12.  3. 13. 11.]
 [ 6. 13.  8.  5. 11.  4.  1.  3. 15.  2.  0. 12. 14.  9.  7. 10.]
 [14.  2.  0.  8. 15.  7. 10.  4.  6.  9.  1. 12.  5. 11.  3. 13.]
 [13.  3.  5.  9. 10.  7.  2. 11.  1.  6.  4. 12. 14.  0.  8. 

In [279]:
y_pred_score

array([[13.,  3.,  5., 11.,  7., 10.,  9.,  2.,  1., 12., 14.,  4.,  8.,
         6.,  0., 15.],
       [12., 15.,  8.,  0., 13.,  2.,  5.,  1.,  6.,  3., 10.,  4.,  9.,
        14.,  7., 11.],
       [ 5.,  2.,  0., 10., 15., 11.,  8.,  6., 12., 14.,  4.,  1.,  7.,
         3., 13.,  9.],
       [ 5.,  3., 13., 11.,  7., 10.,  9.,  2.,  1., 12., 14.,  4.,  8.,
         6.,  0., 15.],
       [ 9.,  8.,  3., 11., 13.,  0.,  6.,  1.,  4., 10.,  2., 14.,  5.,
        15.,  7., 12.],
       [ 4., 10.,  2.,  9.,  7., 11.,  1.,  5.,  0., 13.,  3.,  8., 15.,
        14.,  6., 12.],
       [10., 15.,  8.,  2.,  6., 14.,  7.,  0., 11.,  3.,  1., 13., 12.,
         9.,  4.,  5.],
       [ 9.,  8.,  3., 13., 11.,  4.,  1., 10.,  2.,  6., 12., 14.,  7.,
         5.,  0., 15.],
       [ 3., 13.,  5.,  9., 10.,  7., 11.,  2.,  1., 12.,  4.,  6., 14.,
         0.,  8., 15.],
       [ 9.,  0.,  3.,  4.,  5.,  6.,  1., 12.,  8., 15.,  7., 11., 10.,
         2., 13., 14.],
       [ 2.,  8., 10., 15.,  4

In [280]:
for i in range(np.shape(k)[0]):
    print(i)
    for j in y_sorted_score[i]:
        print(s[int(j)])

0
pringles_bbq
cheez_it_white_cheddar
clif_crunch_chocolate_chip
nutrigrain_apple_cinnamon
detergent
nice_honey_roasted_almonds
listerine_green
campbells_chicken_noodle_soup
aunt_jemima_original_syrup
palmolive_green
vo5_extra_body_volumizing_shampoo
cholula_chipotle_hot_sauce
expo_marker_red
coca_cola_glass_bottle
3m_high_tack_spray_adhesive
vo5_split_ends_anti_breakage_shampoo
1
palmolive_green
vo5_split_ends_anti_breakage_shampoo
expo_marker_red
3m_high_tack_spray_adhesive
pringles_bbq
campbells_chicken_noodle_soup
clif_crunch_chocolate_chip
aunt_jemima_original_syrup
coca_cola_glass_bottle
cheez_it_white_cheddar
nice_honey_roasted_almonds
cholula_chipotle_hot_sauce
listerine_green
vo5_extra_body_volumizing_shampoo
detergent
nutrigrain_apple_cinnamon
2
clif_crunch_chocolate_chip
campbells_chicken_noodle_soup
3m_high_tack_spray_adhesive
nice_honey_roasted_almonds
vo5_split_ends_anti_breakage_shampoo
nutrigrain_apple_cinnamon
expo_marker_red
coca_cola_glass_bottle
palmolive_green
vo5_

In [281]:
f=open("../files/TestNames_4000","rb")
Names= pickle.load(f)
len(Names)
f.close()

In [282]:
[print(str(i)+"\t"+str(Names[i])+"\n") for i in range(15)]

0	['tr', 'hard_single_3.jpg']

1	['tr', 'test_1.jpg']

2	['tr', 'easy_single_3.jpg']

3	['tr', 'hard_multi_1.jpg']

4	['tr', 'hard_single_1.jpg']

5	['tr', 'easy_multi_1.jpg']

6	['tr', 'easy_single_1.jpg']

7	['tr', 'hard_multi_3.jpg']

8	['tr', 'hard_single_2.jpg']

9	['tr', 'test_3.jpg']

10	['tr', 'easy_multi_2.jpg']

11	['tr', 'easy_multi_3.jpg']

12	['tr', 'test_2.jpg']

13	['tr', 'easy_single_2.jpg']

14	['tr', 'hard_multi_2.jpg']



[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [283]:
tfk=k

In [284]:
k1=np.vstack([tfk,Arr])
from sklearn.feature_extraction.text import TfidfTransformer
tfr = TfidfTransformer(smooth_idf=False)
transf=tfr.fit_transform(k1)
k1= transf.toarray()
print(k1.shape)
tf=k1[len(tfk):]

/usr/local/lib/python3.5/dist-packages/sklearn/feature_extraction/text.py:1242: RuntimeWarning: divide by zero encountered in true_divide
  idf = np.log(n_samples / df) + 1


(3471, 4000)


In [285]:
k1=k1[0:len(tfk)]

In [286]:
z=np.dot(k1,tf.transpose())

In [287]:
np.shape(z)

(15, 3456)

In [288]:
y_pred_score1=clf.decision_function(tfk)
y_pred_score1

array([[-6.43605546e+00,  5.70497190e+00,  8.91297365e+00,
         4.19012038e+01, -1.12538888e+00,  3.99426626e+01,
        -6.19402637e+00,  2.05477174e+01, -3.63753087e+00,
         1.51814355e+01,  1.96075645e+01,  2.20957360e+01,
         2.77742324e+00,  4.29134353e+01,  2.16055226e+00,
        -1.08241391e+01],
       [-7.26797662e-01, -9.62244285e-01, -9.49413460e-01,
        -1.05895594e+00, -1.11966036e+00, -9.50522470e-01,
        -1.00654889e+00, -1.38965787e+00, -7.22640235e-01,
        -1.14914104e+00, -1.06040709e+00, -1.43482269e+00,
         2.68393090e+00, -8.50633406e-01, -1.14950825e+00,
        -5.23434363e-01],
       [-5.17037850e-01, -9.72010326e-01, -3.02082038e-01,
        -1.18704916e+00, -9.57239153e-01,  4.79406594e-02,
        -6.78833368e-01, -1.01695120e+00, -6.60844849e-01,
        -1.53004951e+00, -5.29914044e-01, -6.29235217e-01,
        -8.04717104e-01, -1.20336552e+00, -8.25800106e-01,
        -5.75997823e-01],
       [-5.85804792e+00,  6.44837392e

In [289]:
import copy
Netout=copy.deepcopy(z)

In [290]:
for i in range(np.shape(tfk)[0]):
    for j in range(16):
        for l in range(216):
            Netout[i][int(nmidx[j])*216+l]=y_pred_score1[i][j]*(1+np.power(z[i][int(nmidx[j])*216+l], 6))
            #Netout[i][int(nmidx[j])*216+l]=z[i][int(nmidx[j])*216+l]
            #Netout[i][int(nmidx[j])*216+l]=y_pred_score1[i][j]
Netout

array([[-10.82413914, -10.82413914, -10.82413914, ...,  -6.19402637,
         -6.19402637,  -6.19402637],
       [ -0.52343437,  -0.52343436,  -0.52344979, ...,  -1.00654889,
         -1.00654889,  -1.0065489 ],
       [ -0.5759979 ,  -0.57599784,  -0.57599783, ...,  -0.67883338,
         -0.67883338,  -0.6788335 ],
       ...,
       [ -0.86092024,  -0.86092024,  -0.86092024, ...,   0.89158809,
          0.89158809,   0.89158809],
       [ -0.74711971,  -0.74711968,  -0.74711961, ...,  -1.0490459 ,
         -1.04904577,  -1.04904645],
       [-11.12162766, -11.12162766, -11.12162766, ...,   0.40061475,
          0.40061475,   0.40061475]])

In [291]:
Netout1=Netout
for i in range(np.shape(tfk)[0]):
    Netout1[i]=np.argsort(-Netout[i])
Netout1

array([[ 475.,  544.,  524., ...,   81.,   94.,   87.],
       [2898., 2911., 3001., ..., 1763., 1913., 1792.],
       [1107., 1131., 1095., ..., 2314., 2285., 2260.],
       ...,
       [3298., 3316., 3299., ...,  724.,  807.,  841.],
       [3176., 3037., 3075., ...,  544.,  607.,  510.],
       [ 524.,  544.,  475., ...,   79.,  131.,   51.]])

In [292]:
for i in range(np.shape(tfk)[0]):
    print(i)
    for j in range(len(Netout1[i])):
        if j==0:
            print(names[int(Netout1[i][j])])

0
['pringles_bbq' 'N2_150.jpg']
1
['palmolive_green' 'N1_51.jpg']
2
['clif_crunch_chocolate_chip' 'N1_87.jpg']
3
['clif_crunch_chocolate_chip' 'N1_123.jpg']
4
['listerine_green' 'N1_282.jpg']
5
['cholula_chipotle_hot_sauce' 'N2_153.jpg']
6
['nice_honey_roasted_almonds' 'N1_219.jpg']
7
['listerine_green' 'N1_219.jpg']
8
['cheez_it_white_cheddar' 'N1_51.jpg']
9
['listerine_green' 'N2_120.jpg']
10
['campbells_chicken_noodle_soup' 'N1_147.jpg']
11
['expo_marker_red' 'N1_153.jpg']
12
['coca_cola_glass_bottle' 'N1_303.jpg']
13
['vo5_extra_body_volumizing_shampoo' 'N1_174.jpg']
14
['pringles_bbq' 'N1_105.jpg']


In [293]:
direct="../result/"
os.mkdir(direct)
for i in range(len(tfk)):
    filnm,_ =os.path.splitext(Names[i][1])
    with open(os.path.join(direct,filnm+".txt"),"w+") as f:
        for j in range(len(Netout1[i])):
                f.write(names[int(Netout1[i][j])][0]+"_"+names[int(Netout1[i][j])][1]+"\n")
